### ISSUE TITLE
Why there is only arm64-v8a dir for libopencv_java3.so?

### ISSUE THREAD

**Issue by GuoJinyu** [daquexian/daq_example#1]
In other arm type devices，apk cannot be installed successfully.

**Comment by qqqtankqqq** [comment]
download opencv android pack
add the others dir from `OpenCV-android-sdk\sdk\native\libs `

**Comment by daquexian** [comment]
Thanks for your interest in dnnlibrary :) 

The size of the project will increase dramatically because of the opencv lib, so only arm64-v8a opencv lib is added here.

For armv7, you might want to download the corresponding opencv lib manually, just as @qqqtankqqq says (thank you @qqqtankqqq )

Please feel free to reply if your trouble is not solved.

**Comment by GuoJinyu** [comment]
Thanks all.
The apk can be installed successfully now, but there is same problem with libdaq-jni.so which is in dnnlibrary. Since it is a library, should armeabi-v7a and armeabi be supported？

**Comment by daquexian** [comment]
> Thanks all.
> The apk can be installed successfully now, but there is same problem with libdaq-jni.so which is in dnnlibrary. Since it is a library, should armeabi-v7a and armeabi be supported？

Yes, this project is only an example, so only armv8 lib is included. Frankly speaking I forget whether there is an armeabi-v7a library included in [aar package](https://github.com/daquexian/DNNLibrary#if-you-are-an-android-app-developer-and-want-it-to-work-out-of-the-box). If not, I will manage to added it.

**Comment by SiR0N** [comment]
Hi! 

I just add the libraries and I could install the app but It gives me that error:

```
Process: me.daquexian.nnapiexample, PID: 8914
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/base.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_dependencies_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_resources_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_0_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_1_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_2_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_3_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_4_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_5_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_6_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_7_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_8_apk.apk", zip file "/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/base.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_resources_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/me.daquexian.nnapiexample-iYHFilN1b7FoByjrk8F2xg==/split_lib_slice_9_apk.apk!/lib/x86, 
/system/lib]]] couldn't find "libdaq-jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at me.daquexian.dnnlibrary.ModelBuilder.<clinit>(ModelBuilder.java:13)
        at me.daquexian.nnapiexample.MainActivity.onCreate(MainActivity.java:86)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4784)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
E/AndroidRuntime:     at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4743)
        at android.app.ActivityThread.access$3200(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

it happens at running: 
`ModelBuilder modelBuilder = new ModelBuilder();`

I am running it in Android 9.0 x84 (emulator)

**Comment by daquexian** [comment]
@SiR0N The package doesn't contain x86 or x64 .so. It will be resolved soon.
